ministryofjustice/prisoner-content-hub-feedback-exporter

.circleci/config.yml
Dockerfile
helm_deploy/prisoner-content-hub-feedback-exporter/templates/job.yaml
package-lock.json
package.json

https://trello.com/c/VoC0hras
* Fix build-info so correct app version is recorded
* Update dependencies
* Correct alerts channel
* Remove outdated check - this is more useful for the template project
* Correct job name, only record previous 3 failures and most recent successful job
* Moved to use prepare rather than post install script hook to install husky
Nope

Various fixes

---

.circleci/config.yml
helm_deploy/values-prod.yaml
helm_deploy/values-staging.yaml
job/config.ts
job/feedbackJob.ts
job/feedbackRetriever.ts

https://trello.com/c/VoC0hras
Roll out job to staging and prod
Also addressing a couple of PR comments
Set up secrets but will need to guide this change out to ensure been set up appropriately

Deploying to staging and production

---

.circleci/config.yml

Staging deploy is broken as requires a docker image to be built in the same pipeline.

Fix build so can deploy to staging

---

helm_deploy/prisoner-content-hub-feedback-exporter/templates/job.yaml

https://trello.com/c/VoC0hras
Amend the cron job to run at a more appropriate time for local comms managers and the hub team. The time is also aligned with the Slack workflow notification

Update cron job

---

.circleci/config.yml

No - just updating hmpps orb for build
To pick up changelog publishing

Updating circle ci orb to pick up change log

---

job/run.ts

https://trello.com/b/cnqZuHWO
The job wasn't failing if an error occurred, this should now hopefully now set the status appropriately.

Fixing error alerting

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json

https://trello.com/c/eS1TSagC
Update dependencies and version of node 
Need to monitor that feedback still gets posted to the channel

New version of node and bumping dependencies

---

package-lock.json

https://trello.com/c/tPMdK5QX
In response to CVE-2022-0235

vulnerability update CVE-2022-0235

---

job/config.ts

Update range for testing

---

job/config.ts

Amended to run on a Monday
https://trello.com/c/3Nt7wFgJ
Amend weekly feedback schedule

Update weekly feedback day

---

job/config.ts

Update weekly feedback to Wednesday

---

job/config.ts

Pulls data for the last ten days to cover the relevant testing time period. The range will then be amended to the 7-day agreed schedule

Update config to run on Monday

---

job/config.ts

https://trello.com/c/3Nt7wFgJ
To regulate the feedback to the agreed 7 day schedule

Update config range to run 7 day schedule

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json

Update dependencies and node version

---

package-lock.json

n/a
n/a
update dependencies
n/a
n/a
n/a

npm_update_dependencies

---

.circleci/config.yml
helm_deploy/prisoner-content-hub-feedback-exporter/templates/job.yaml

Update config for cron and npm

---

package-lock.json
package.json

Update dependencies 2024-03-18

---

.circleci/config.yml

Fix circleci contexts

---

.circleci/config.yml
package-lock.json
package.json

Update dependencies 2024-04-29

---

package-lock.json
package.json

Update dependencies 2024-06-12

---

package-lock.json
package.json

Update dependencies 2024-08-14

---

package-lock.json
package.json

Update dependencies 2024-09-02

---

.gitignore
README.md
database/migrations/20250226134800-create-feedback-table.js
database/migrations/20250303093300-feedback-table-datetime.js
knexfile.js
package-lock.json
package.json

Yes.
Runs migrations for new Feedback database
No

LNP-1133: Add Postgres database, knex etc

---

package-lock.json
package.json

Update dependencies 2025-03-07

---

package-lock.json
package.json

Update dependencies 2025-03-14
